import { Platform } from 'react-native'

export const send = 'md-send'
export const add = Platform.OS === 'ios' ? 'ios-add' : 'md-add'
export const link = Platform.OS === 'ios' ? 'ios-link' : 'md-link'
export const more = Platform.OS === 'ios' ? 'ios-more' : 'md-more'
export const mail = Platform.OS === 'ios' ? 'ios-mail' : 'md-mail'
export const lock = Platform.OS === 'ios' ? 'ios-lock' : 'md-lock'
export const alert = Platform.OS === 'ios' ? 'ios-alert' : 'md-alert'
export const trash = Platform.OS === 'ios' ? 'ios-trash' : 'md-trash'
export const podium = Platform.OS === 'ios' ? 'ios-podium' : 'md-podium'
export const user = Platform.OS === 'ios' ? 'ios-contact' : 'md-contact'
export const search = Platform.OS === 'ios' ? 'ios-search' : 'md-search'
export const discuss = Platform.OS === 'ios' ? 'ios-chatboxes' : 'md-chatboxes'
export const noti = Platform.OS === 'ios' ? 'ios-notifications' : 'md-notifications'
export const up = Platform.OS === 'ios' ? 'ios-arrow-dropup' : 'md-arrow-dropup-circle'
export const down = Platform.OS === 'ios' ? 'ios-arrow-dropdown' : 'md-arrow-dropdown-circle'